export const CURRENCY_LOAD = "CURRENCY_LOAD";
export const ADD_TO_CARD = "ADD_TO_CARD";
export const INCREMENT_PRODUCT = "INCREMENT_PRODUCT";
export const DECREMENT_PRODUCT = "DECREMENT_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const CHANGE_CURRENCY = "CHANGE_CURRENCY";
